name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GHC and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.12.1'
          cabal-version: '3.14.1.1'  # Ensure compatibility with GHC 9.12.1, todo!()

      - name: Cache Cabal store
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Build the project
        run: cabal build
        
      - name: Run interpreted normalization
        run: cabal run hvml -- run ./book/feat_hoas.hvml
        
      - name: Run compiled normalization
        run: cabal run hvml -- run ./book/feat_hoas.hvml -c
        
      - name: Run interpreted collapse
        run: cabal run hvml -- run ./book/enum_lam_smart.hvml -C
        
      - name: Run compiled collapse
        run: cabal run hvml -- run ./book/enum_lam_smart.hvml -C -c
